### ISSUE TITLE
Error: The system cannot find the specified file.

### ISSUE THREAD

**Issue by TrashTWellington** [logdot/Highfleet-Modloader#10]
Hello, this error shows when executing the HighfleetModloader.exe file. I imagine this is because I have the GOG version and not the steam version? I tried to fix this myself but the window name of the GOG version doesn't seem to be any different from what I could see.

**Comment by logdot** [comment]
Yo. Really sorry. I didn’t see this until now.

The specific error message you are seeing should be unrelated to the GOG version of the game. However, none of the mods that use the modloader currently support the GOG version.

If you’ve tried with the steam version and get the same error message when running the modloader as an administrator, re-open the issue.

You can also reach me through discord, username logdot, or though the highfleet discord server https://discord.gg/unofficial-highfleet-community-735016620719603833 

Now I just need to figure out how to set up notifications so I don’t miss any other issues.
